package matcher

import (
	"go/ast"
	"go/token"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

type (
	PackageID   = string
	FileName    = string
	GeneratedBy = string
)

const (
	PatternAll = "./..."
	PatternStd = "std"

	// LoadDepts load all dependencies
	LoadDepts = packages.NeedImports | packages.NeedDeps
	LoadMode  = packages.NeedTypesInfo |
		packages.NeedName |
		packages.NeedFiles |
		packages.NeedExportFile |
		packages.NeedCompiledGoFiles |
		packages.NeedTypes |
		packages.NeedSyntax |
		packages.NeedTypesInfo |
		packages.NeedModule
)

// ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ Loader ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

type LoadFlags struct {
	buildTag  string // comma-separated list of extra build tags (see: go help buildconstraint)
	test      bool   // load includes tests packages
	loadDepts bool   // load all dependencies, may heavily slow
}

type Loader struct {
	FSet      *token.FileSet
	Init      []*packages.Package
	All       map[PackageID]*packages.Package
	Generated map[string]string
}

func NewLoader() *Loader {
	return &Loader{
		FSet:      token.NewFileSet(),
		Init:      []*packages.Package{},
		All:       map[PackageID]*packages.Package{},
		Generated: map[FileName]GeneratedBy{},
	}
}

// Load Packages
// dir: run the build system's query tool
// patterns: (see: packages.Load)
func (d *Loader) Load(dir string, patterns []string, flags LoadFlags) {
	mode := LoadMode
	if flags.loadDepts {
		mode |= LoadDepts
	}

	dir, err := filepath.Abs(dir)
	panicIfErr(err)

	cfg := &packages.Config{
		Fset:       d.FSet,
		Mode:       mode,
		Tests:      flags.test,
		Dir:        dir,
		BuildFlags: []string{"-tags=" + flags.buildTag},
	}
	d.Init, err = packages.Load(cfg, patterns...)
	panicIfErr(err)

	if len(d.Init) == 0 {
		errLog("no packages found")
	}

	packages.Visit(d.Init, nil, func(p *packages.Package) {
		for _, err := range p.Errors {
			errLog(err)
		}

		// Gather all packages
		d.All[p.ID] = p

		// Gather generated files
		for _, file := range p.Syntax {
			if gen, is := Generator(file); is {
				f := p.Fset.File(file.Pos())
				d.Generated[f.Name()] = gen
			}
		}
	})
}

// ↓↓↓↓↓↓↓↓↓↓↓↓ copy from go1.21 ast.IsGenerated ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

// IsGenerated reports whether the file was generated by a program,
// not handwritten, by detecting the special comment described
// at https://go.dev/s/generatedcode.
//
// The syntax tree must have been parsed with the ParseComments flag.
// Example:
//
//	f, err := parser.ParseFile(fset, filename, src, parser.ParseComments|parser.PackageClauseOnly)
//	if err != nil { ... }
//	gen := ast.IsGenerated(f)
//
// copy from go1.21 ast.IsGenerated
func IsGenerated(file *ast.File) bool {
	_, ok := Generator(file)
	return ok
}

// Generator copy from go1.21 ast.IsGenerated
func Generator(file *ast.File) (string, bool) {
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if comment.Pos() > file.Package {
				break // after package declaration
			}
			// opt: check Contains first to avoid unnecessary array allocation in Split.
			const prefix = "// Code generated "
			if strings.Contains(comment.Text, prefix) {
				for _, line := range strings.Split(comment.Text, "\n") {
					if rest, ok := strings.CutPrefix(line, prefix); ok {
						if gen, ok := strings.CutSuffix(rest, " DO NOT EDIT."); ok {
							return gen, true
						}
					}
				}
			}
		}
	}
	return "", false
}
